name: Exemplo de Workflow Paralelo

on: [push]

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Job A
        run: echo "Executando Job A" && sleep 10

  jobB:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Job B
        run: echo "Executando Job B" && sleep 10

  jobC:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Job C
        run: echo "Executando Job C" && sleep 10

  jobAA:
    needs: [jobA, JobB, JobC]
    runs-on: ubuntu-latest
    steps:
      - name: Executar Job AA
        run: echo "Executando Job AA depois de Job A"

  jobBB:
    needs: [jobA, JobB, JobC]
    runs-on: ubuntu-latest
    steps:
      - name: Executar Job BB
        run: echo "Executando Job BB depois de Job B"

  jobCC:
    needs: [jobA, JobB, JobC]
    runs-on: ubuntu-latest
    steps:
      - name: Executar Job CC
        run: echo "Executando Job CC depois de Job C"