name: Exemplo de Workflow Paralelo

on: [push]

jobs:
  jobA:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [runner-01, runner-02, runner-03]
    steps:
      - name: Executar Job A
        run: echo "Executando Job A" && sleep 40

  jobB:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [runner-01, runner-02, runner-03]
    steps:
      - name: Executar Job B
        run: echo "Executando Job B" && sleep 60

  jobC:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [runner-01, runner-02, runner-03]
    steps:
      - name: Executar Job C
        run: echo "Executando Job C" && sleep 80

  jobAA:
    needs: [jobA, jobC]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [runner-01, runner-02, runner-03]
    steps:
      - name: Executar Job AA
        run: echo "Executando Job AA depois de Job A e Job C"

  jobBB:
    needs: [jobB, jobC]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [runner-01, runner-02, runner-03]
    steps:
      - name: Executar Job BB
        run: echo "Executando Job BB depois de Job B e Job C"

  jobCC:
    needs: [jobA, jobB]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [runner-01, runner-02, runner-03]
    steps:
      - name: Executar Job CC
        run: echo "Executando Job CC depois de Job A e Job B"

