name: Exemplo de Workflow Paralelo
on: [push]
jobs:
  jobA:
    runs-on: [runner-01,runner-02,runner-03]
    steps:
      - name: Executar Job A
        run: echo "Executando Job A" && sleep 40

  jobB:
    runs-on: [runner-01,runner-02,runner-03]
    steps:
      - name: Executar Job B
        run: echo "Executando Job B" && sleep 60

  jobC:
    runs-on: [runner-01,runner-02,runner-03]
    steps:
      - name: Executar Job C
        run: echo "Executando Job C" && sleep 80

  jobAA:
    needs: [jobA, JobC]
    runs-on: [runner-01,runner-02,runner-03]
    steps:
      - name: Executar Job AA
        run: echo "Executando Job AA depois de Job A"

  jobBB:
    needs: [jobB, JobC]
    runs-on: [runner-01,runner-02,runner-03]
    steps:
      - name: Executar Job BB
        run: echo "Executando Job BB depois de Job B"

  jobCC:
    needs: [jobA, JobB]
    runs-on: [runner-01,runner-02,runner-03]
    steps:
      - name: Executar Job CC
        run: echo "Executando Job CC depois de Job C"

